### PR TITLE
setup complete

### PR DESCRIPTION
**Pull request by RobertShock**

### CODE REVIEW

**Comment by RobertShock** [comment]
setup completed.  check it out .

**Comment by kstoops815** [comment]
@RobertShock overall looks good. Just a few things to add: Let's go ahead and update the dependencies in the grunt file. (ex. instead of dist/app.js, change to javascripts/app.js). Also, please add "use strict" to all of the javascript files so that we don't forget that. And add @ import "variables" to the main.scss.  Thanks!

**Comment by waamber** [comment]
We should also add this to all of the controllers as well, just to have it in there :)

```
app.controller("CTRL NAME", function () {
 
  };
});
```

**Comment by DreRandaci** [comment]
on line 13 in the predef array there's a missing quotation for "app". that's what's making the Gruntfile invalid @RobertShock

**Comment by waamber** [comment]
👍

**Pull request merged**
