### PR TITLE
changed firebase calls, reordered some promise calls, added data to json

### PR DESCRIPTION
**Pull request by DreRandaci**

### CODE REVIEW

**Comment by DreRandaci** [comment]
please check this @waamber @kstoops815 

everyone should have at least one board and a few pins to start

**Comment by kstoops815** [comment]
@DreRandaci I noticed you changed the pin.board_id to pin.url on the singleboard partial. Can you change that on each instance of printing pins to a page? I think the others are pins.html and tried.html. i didn't see those changes in the files changed.

**Comment by waamber** [comment]
👍

**Comment by kstoops815** [comment]
👍

**Pull request merged**
